// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.3
// Project name: SquareLine_Project

#include "../ui.h"

void ui_compassScreen_screen_init(void)
{
ui_compassScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_compassScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_compassScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_compassScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_compassImg = lv_img_create(ui_compassScreen);
lv_img_set_src(ui_compassImg, &ui_img_menu_compassicon_png);
lv_obj_set_width( ui_compassImg, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_compassImg, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_compassImg, 0 );
lv_obj_set_y( ui_compassImg, -10 );
lv_obj_set_align( ui_compassImg, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_compassImg, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_compassImg, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_compassLabel = lv_label_create(ui_compassScreen);
lv_obj_set_width( ui_compassLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_compassLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_compassLabel, 0 );
lv_obj_set_y( ui_compassLabel, -5 );
lv_obj_set_align( ui_compassLabel, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_compassLabel,"Compass");
lv_obj_set_style_text_color(ui_compassLabel, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_compassLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_compassLabel, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_compassScreen, ui_event_compassScreen, LV_EVENT_ALL, NULL);

}
