// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.3
// Project name: SquareLine_Project

#include "../ui.h"

void ui_radioCheckScreen_screen_init(void)
{
ui_radioCheckScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_radioCheckScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_radioCheckScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_radioCheckScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_radioCheckImg = lv_img_create(ui_radioCheckScreen);
lv_img_set_src(ui_radioCheckImg, &ui_img_menu_radioicon_png);
lv_obj_set_width( ui_radioCheckImg, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_radioCheckImg, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_radioCheckImg, 0 );
lv_obj_set_y( ui_radioCheckImg, -10 );
lv_obj_set_align( ui_radioCheckImg, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_radioCheckImg, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_radioCheckImg, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_radioCheckLabel = lv_label_create(ui_radioCheckScreen);
lv_obj_set_width( ui_radioCheckLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_radioCheckLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_radioCheckLabel, 0 );
lv_obj_set_y( ui_radioCheckLabel, -5 );
lv_obj_set_align( ui_radioCheckLabel, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_radioCheckLabel,"Radio Check");
lv_obj_set_style_text_color(ui_radioCheckLabel, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_radioCheckLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_radioCheckLabel, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

}
