// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.3
// Project name: SquareLine_Project

#include "../ui.h"

void ui_welcomeScreen_screen_init(void)
{
ui_welcomeScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_welcomeScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_welcomeScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_welcomeScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Welcome = lv_label_create(ui_welcomeScreen);
lv_obj_set_width( ui_Welcome, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Welcome, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Welcome, LV_ALIGN_CENTER );
lv_label_set_text(ui_Welcome,"Welcome");
lv_obj_set_style_text_color(ui_Welcome, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Welcome, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Welcome, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_welcomeScreen, ui_event_welcomeScreen, LV_EVENT_ALL, NULL);

}
