// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.3
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void up_Animation( lv_obj_t *TargetObject, int delay);

// SCREEN: ui_welcomeScreen
void ui_welcomeScreen_screen_init(void);
void ui_event_welcomeScreen( lv_event_t * e);
lv_obj_t *ui_welcomeScreen;
lv_obj_t *ui_Welcome;

// SCREEN: ui_compassScreen
void ui_compassScreen_screen_init(void);
void ui_event_compassScreen( lv_event_t * e);
lv_obj_t *ui_compassScreen;
lv_obj_t *ui_compassImg;
lv_obj_t *ui_compassLabel;

// SCREEN: ui_radioCheckScreen
void ui_radioCheckScreen_screen_init(void);
lv_obj_t *ui_radioCheckScreen;
lv_obj_t *ui_radioCheckImg;
lv_obj_t *ui_radioCheckLabel;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void up_Animation( lv_obj_t *TargetObject, int delay)
{

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_welcomeScreen( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_SCREEN_LOADED) {
      _ui_screen_change( &ui_compassScreen, LV_SCR_LOAD_ANIM_OVER_TOP, 200, 1000, &ui_compassScreen_screen_init);
}
}
void ui_event_compassScreen( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_radioCheckScreen, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_radioCheckScreen_screen_init);
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_basic_init(dispp);
lv_disp_set_theme(dispp, theme);
ui_welcomeScreen_screen_init();
ui_compassScreen_screen_init();
ui_radioCheckScreen_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_welcomeScreen);
}
