// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.3
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
void up_Animation( lv_obj_t *TargetObject, int delay);
// SCREEN: ui_welcomeScreen
void ui_welcomeScreen_screen_init(void);
void ui_event_welcomeScreen( lv_event_t * e);
extern lv_obj_t *ui_welcomeScreen;
extern lv_obj_t *ui_Welcome;
// SCREEN: ui_compassScreen
void ui_compassScreen_screen_init(void);
void ui_event_compassScreen( lv_event_t * e);
extern lv_obj_t *ui_compassScreen;
extern lv_obj_t *ui_compassImg;
extern lv_obj_t *ui_compassLabel;
// SCREEN: ui_radioCheckScreen
void ui_radioCheckScreen_screen_init(void);
extern lv_obj_t *ui_radioCheckScreen;
extern lv_obj_t *ui_radioCheckImg;
extern lv_obj_t *ui_radioCheckLabel;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_horizontal_lines_png);   // assets/horizontal_lines.png
LV_IMG_DECLARE( ui_img_menu_compassicon_png);   // assets/menu_compassIcon.png
LV_IMG_DECLARE( ui_img_menu_radioicon_png);   // assets/menu_radioIcon.png

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
