// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.3
// Project name: SquareLine_Project

#include "../ui.h"

void ui_comp_compassScreen_create_hook( lv_obj_t * comp)
{
}
