// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.3
// Project name: SquareLine_Project

#include "../ui.h"

// COMPONENT compassScreen

lv_obj_t *ui_compassScreen_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_compassScreen;
cui_compassScreen = lv_img_create(comp_parent);
lv_obj_set_width( cui_compassScreen, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_compassScreen, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( cui_compassScreen, LV_ALIGN_CENTER );
lv_obj_add_flag( cui_compassScreen, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( cui_compassScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_img_recolor(cui_compassScreen, lv_color_hex(0xFFFF00), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(cui_compassScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_COMPASSSCREEN_NUM);
children[UI_COMP_COMPASSSCREEN_COMPASSSCREEN] = cui_compassScreen;
lv_obj_add_event_cb(cui_compassScreen, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_compassScreen, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_compassScreen_create_hook(cui_compassScreen);
return cui_compassScreen; 
}

